const mongoose = require("mongoose");
const Schema = mongoose.Schema;
/**
 * WeekHistoryModel
 *
 * written by Marcus Jefferson 8/4/2020
 *
 * This model holds the histograms and top 5
 * statistics generated by the PastWeekStatsJob
 */

const weekLongHistorySchema = new Schema(
  {
    user_mongo_id: {
      type: String,
    },
    user_spotify_id: {
      type: String,
    },
    pretty_date: {
      type: String,
    },
    unique_track_count: {
      type: Number,
      default: 0,
    },
    unique_album_count: {
      type: Number,
      default: 0,
    },
    unique_artist_count: {
      type: Number,
      default: 0,
    },
    unique_genre_count: {
      type: Number,
      default: 0,
    },
    listening_time: {
      type: Object,
      default: null,
    },
    top_five: {
      type: Object,
      default: null,
    },
    track_histogram: {
      type: [Object],
      default: {
        track_id: String,
        occurances: Number,
      },
    },
    album_histogram: {
      type: [Object],
      default: {
        album_id: String,
        occurances: Number,
      },
    },
    artist_histogram: {
      type: [Object],
      default: {
        artist_id: String,
        occurances: Number,
      },
    },
    genre_histogram: {
      type: [Object],
      default: {
        genre: String,
        occurances: Number,
      },
    },
  },
  { timestamps: true }
);

const WeekHistoryModel = mongoose.model(
  "WeekHistoryModel",
  weekLongHistorySchema
);

/**
 * Statistic Log History
 *
 * Dunno what else to really call this, but
 * escentially stores arrays of pointers for
 * each consecutively recorded history model.
 * So far it only includes an array of pointers
 * to a stats from a week long listening period,
 * but could include pointers to longer periods of
 * time pretty easily.
 */
const statHistoryLogSchema = new Schema(
  {
    user_mongo_id: {
      type: String,
    },
    user_spotify_id: {
      type: String,
    },
    stats_from_each_week: {
      type: [String],
      default: [],
    },
  },
  { timestamps: true }
);

const StatisticLogHistoryModel = mongoose.model(
  "StatisticLogHistoryModel",
  statHistoryLogSchema
);

module.exports = { WeekHistoryModel, StatisticLogHistoryModel };
